---
piplant:
  poll_interval: 5s
  render_interval: 1hr
  debug: true
  plants:
    - name: fukien_tea
      water_threshold: 25%
      min_temp: 8
      max_temp: 28
      icon: fukien_tea.png
    - name: china_doll
      water_threshold: 35%
      min_temp: 5
      max_temp: 25.5
      icon: china_doll.png
    - name: emerald_palm
      water_threshold: 10%
      min_temp: 7
      max_temp: 28
      icon: palm.png
  sensors:
    hygrometers:
      - plant: fukien_tea
        package: sensors.hygrometer.aideepen
        kwargs:
          mock: true
          adc_channel: 1
          calibrated_max_val: 0.70
      - plant: china_doll
        package: sensors.hygrometer.aideepen
        kwargs:
          mock: true
          adc_channel: 2
          calibrated_max_val: 0.68
      - plant: emerald_palm
        package: sensors.hygrometer.aideepen
        kwargs:
          mock: true
          adc_channel: 3
          calibrated_max_val: 0.67
    environment:
      - name: SensorHub
        package: sensors.environment.dockerpi
        kwargs:
          mock: true
    device:
      - name: RPi
        package: sensors.device.raspberrypi
        kwargs:
          mock: true
display:
  package: display.rpi_epd3in7
  kwargs:
    mock: true
  enabled: true
  refresh_interval: 1hr
  skip_splash_screen: false
lightmanager:
  autodiscovery: disabled
  geo_city: "Dublin"
  device_query_interval: 2m
  device_type: lifx
  device_groups:
    - motion_lights:
      - mac: d0:73:d5:6d:8f:b1
        ip: 192.168.1.27
      - mac: d0:73:d5:43:c8:eb
        ip: 192.168.1.40 
    - desk_lamp:
      - mac: d0:73:d5:6b:cc:29
        ip: 192.168.1.28
      - mac: d0:73:d5:6D:59:2d
        ip: 192.168.1.29 
      - mac: d0:73:d5:6a:12:7a
        ip: 192.168.1.30
      - mac: d0:73:d5:6b:61:51
        ip: 192.168.1.39
  motion_detection:
    timeout: 15m
    on_motion_trigger:
      transition: 0s
      hsbk:
        brightness: 45%
        kelvin: 3000
    on_motion_timeout:
      transition: 5s
      hsbk:
        brightness: 0%
        kelvin: 3000
    device_groups:
      - motion_lights
  schedules:
    - name: sleep
      time: "00:00"
      hsbk:
        brightness: 0%
        kelvin: 2000
      device_groups:
        - desk_lamp
    - name: wakeup
      time: "07:30"
      transition: 15m
      hsbk:
        brightness: 80%
        kelvin: 2000
      device_groups:
        - desk_lamp
    - name: daytime
      time: "08:00"
      transition: 10m
      hsbk:
        brightness: 100%
        kelvin: 5000
      device_groups:
        - desk_lamp
    - name: evening
      time: "20:00"
      transition: 5h
      hsbk:
        brightness: 80%
        kelvin: 3500
      device_groups:
        - desk_lamp
    - name: nightlight
      time: "21:00"
      transition: 10m
      hsbk:
        brightness: 65%
        kelvin: 2750
      device_groups:
        - desk_lamp
    - name: sleep
      time: "23:00"
      transition: 1m
      hsbk:
        brightness: 0%
        kelvin: 2000
      device_groups:
        - desk_lamp