---
piplant:
  display:
    enabled: true
    driver:
      package_ref: epd
    refresh_interval: 1hr
    skip_splash_screen: false
  hygrometers:
    sensors:
      package_refs:
        - hygrometer-adc-1
        - hygrometer-adc-2
        - hygrometer-adc-3
  device:
    sensors:
      package_refs:
        - rpi-stats
  environment:
    temperature: 
      sensors:
        package_refs:
          - sensorhub
    humidity: 
      sensors:
        package_refs:
          - sensorhub
    brightness:
      sensors:
        package_refs:
          - sensorhub
    pressure: 
      sensors:
        package_refs:
          - sensorhub
    motion: 
      sensors:
        package_refs:
          - sensorhub
  lights:
    schedule_manager:
      enabled: true
      device_query_interval: 2m
      device_groups:
        package_refs:
          - lifx-group-plant-lights
      schedules:
        - name: sleep
          time: "00:00"
          hsbk:
            brightness: 0%
            kelvin: 2000
        - name: daytime
          time: "08:00"
          transition: 10m
          hsbk:
            brightness: 100%
            kelvin: 5000
        - name: evening
          time: "20:00"
          transition: 5h
          hsbk:
            brightness: 80%
            kelvin: 3500
        - name: sleep
          time: "23:00"
          transition: 1m
          hsbk:
            brightness: 0%
            kelvin: 2000
    motion_trigger_manager:
      enabled: true
      timeout: 15m
      sensors:
        package_refs:
          - sensorhub
      device_groups:
        package_refs:
          - lifx-group-motion-lights
      on_motion_trigger:
        transition: 0s
        hsbk:
          brightness: 45%
          kelvin: 3000
      on_motion_timeout:
        transition: 10s
        hsbk:
          brightness: 0%
          kelvin: 3000
packages:
  - name: hygrometer-adc-1
    package: 
      module: sensor.hygrometer.aideepen.capacitivehygrometer
      kwargs:
        adc_channel: 1
        min_value: 0.30
        max_value: 0.70
        dry_value_percentage: 25
  - name: hygrometer-adc-2
    package: 
      module: sensor.hygrometer.aideepen.capacitivehygrometer
      kwargs:
        adc_channel: 2
        min_value: 0.30
        max_value: 0.68
        dry_value_percentage: 35
  - name: hygrometer-adc-3
    package: 
      module: sensor.hygrometer.aideepen.capacitivehygrometer
      kwargs:
        adc_channel: 3
        min_value: 0.30
        max_value: 0.67
        dry_value_percentage: 10
  - name: sensorhub
    package: 
      module: sensor.environment.dockerpi.sensorhub
  - name: rpi-stats
    package: 
      module: sensor.device.raspberrypi.devicestatistics
  - name: epd
    package: 
      remote_module: rpi_epd3in7.epd
      module: display.driver
  - name: lifx-example-light-1
    package:
      remote_module: lifxlan.light
      module: light.device
      kwargs:
        mac_addr: d0:73:d5:00:00:01
        ip_addr: 192.168.1.2
  - name: lifx-example-light-2
    package:
      remote_module: lifxlan.light
      module: light.device
      kwargs:
        mac_addr: d0:73:d5:00:00:02
        ip_addr: 192.168.1.3
  - name: lifx-example-light-3
    package:
      remote_module: lifxlan.light
      module: light.device
      kwargs:
        mac_addr: d0:73:d5:00:00:03
        ip_addr: 192.168.1.4
  - name: lifx-group-plant-lights
    package:
      module: light.device_group.lifx.device_group
      kwargs:
        name: plant_lights
        devices:
          package_refs:
            - lifx-example-light-1
            - lifx-example-light-2
  - name: lifx-group-motion-lights
    package:
      module: light.device_group.lifx.device_group
      kwargs:
        name: motion_lights
        devices:
          package_refs:
            - lifx-example-light-3