---
- name: sqlite-driver
  package:
    module: database.driver.sqlite3.driver
    kwargs:
      dbdata_path: piplant.db
- name: hygrometer-adc-1
  package: 
    module: sensor.hygrometer.aideepen.capacitivehygrometer
    kwargs:
      name: "Fukien Tea"
      adc_channel: 1
      min_value: 0.30
      max_value: 0.70
      dry_value_percentage: 25
- name: hygrometer-adc-2
  package: 
    module: sensor.hygrometer.aideepen.capacitivehygrometer
    kwargs:
      name: "China Doll"
      adc_channel: 2
      min_value: 0.30
      max_value: 0.68
      dry_value_percentage: 35
- name: hygrometer-adc-3
  package: 
    module: sensor.hygrometer.aideepen.capacitivehygrometer
    kwargs:
      name: "Emerald Palm"
      adc_channel: 3
      min_value: 0.30
      max_value: 0.67
      dry_value_percentage: 10
- name: sensorhub
  package: 
    module: sensor.environment.dockerpi.sensorhub
- name: rpi-stats
  package: 
    module: sensor.device.raspberrypi.devicestatistics
- name: epd
  package: 
    remote_module: rpi_epd3in7.epd
    module: display.driver.epd.mock
- name: lifx-group-plant-lights
  package:
    module: light.device_group.lifx.http_group
    kwargs:
      name: Plant Lights
      token: _your_bearer_token_
- name: lifx-group-motion-lights
  package:
    module: light.device_group.lifx.http_group
    kwargs:
      name: Motion Lights
      token: _your_bearer_token_